package com.datacorp.app.payments.domain;

import com.datacorp.app.shared.kernel.CodPrograma;
import com.datacorp.app.shared.kernel.Competencia;
import com.datacorp.app.shared.kernel.Cpf;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.springframework.data.domain.AbstractAggregateRoot;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * JPA entity for PAGAMENTO (Adabas FNR 152, DBID 57).
 * Bounded context: Payments & Folha. This is the single owner of payment data.
 *
 * <p>Generated from DDM {@code PAGAMENTO.ddm} (01-arqueologia/legado-sifap/adabas-ddms/).
 * dateformat=YYYYMMDD: all Adabas N8 date fields are stored as YYYYMMDD integers;
 * mapped to {@link LocalDate} via {@code @Convert(converter = LocalDateN8Converter.class)}
 * (Task T011 — shared kernel converters).
 *
 * <p>⚠️ DEPENDENCY: requires foundational tasks T007–T011 (shared kernel value objects
 * and converters) to compile.
 *
 * <p>PE group mapping (ADR-003):
 * GRP-DESCONTO (CA, max 8) → {@link #descontos} as {@code @ElementCollection}
 * in child table {@code payments.pagamento_desconto}, partitioned by {@code ano_mes_ref}.
 *
 * <p>Status machine (ADR-002): only {@link StatusPagamento}; all transitions validated
 * through {@link StatusPagamento#validateTransitionTo}.
 *
 * <p>SIAFI integration fields are carried but not business-processed by SIFAP. REQ traceability
 * is in SPECIFICATION.md and tasks.md.
 *
 * <p>Super-descriptor indexes (from DDM):
 * <ul>
 *   <li>S1: (num_cpf, ano_mes_ref) — unique per beneficiary per month (REQ-030)</li>
 *   <li>S2: (cod_programa, ano_mes_ref, sit_pagamento) — batch/report queries</li>
 *   <li>S3: (num_ciclo, sit_pagamento) — cycle queries</li>
 * </ul>
 */
@Entity
@Table(
    name = "pagamento",
    schema = "payments",
    uniqueConstraints = {
        @UniqueConstraint(name = "uq_pagamento_cpf_competencia",
                          columnNames = {"num_cpf", "ano_mes_ref"})
    },
    indexes = {
        // S1: super-descriptor AB + AE (DE fields from DDM)
        @Index(name = "idx_pagamento_s1_cpf_competencia",   columnList = "num_cpf, ano_mes_ref"),
        // S2: super-descriptor AD + AE + DA
        @Index(name = "idx_pagamento_s2_prog_comp_status",  columnList = "cod_programa, ano_mes_ref, sit_pagamento"),
        // S3: super-descriptor AF + DA
        @Index(name = "idx_pagamento_s3_ciclo_status",      columnList = "num_ciclo, sit_pagamento"),
        // DT-GERACAO is a DE (descriptor) in the DDM
        @Index(name = "idx_pagamento_dt_geracao",           columnList = "dt_geracao"),
        // NUM-PAGAMENTO is a DE — primary key, already indexed
        @Index(name = "idx_pagamento_num_pagamento",        columnList = "num_pagamento")
    }
)
public class Pagamento extends AbstractAggregateRoot<Pagamento> {

    // ── Identity ──────────────────────────────────────────────────────────────

    /**
     * Unique sequential payment number.
     * DDM: AA NUM-PAGAMENTO N 15 (DE). Generated by DB sequence.
     * BATCHPGT obtains the last value via READ DESCENDING + 1 (BATCHPGT.NSN#L180-L184).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pagamento_seq")
    @SequenceGenerator(name = "pagamento_seq", sequenceName = "payments.pagamento_num_seq",
                       allocationSize = 50)
    @Column(name = "num_pagamento", nullable = false)
    private Long numPagamento;

    /**
     * CPF do beneficiário. DDM: AB NUM-CPF A 11 (DE).
     * Stored as CHAR(11). Value object {@link Cpf} validates Módulo 11 (REQ-001).
     * MASKED in any display/log output (REQ-015, Principle V).
     */
    @NotNull
    @Convert(converter = com.datacorp.app.shared.kernel.CpfConverter.class)
    @Column(name = "num_cpf", nullable = false, length = 11)
    private Cpf cpf;

    /**
     * Cross-reference to BENEFICIARIO.NUM-INSCRICAO. DDM: AC NUM-INSCRICAO N 11.
     * NOT a FK (cross-context boundary — Payments never joins to Beneficiaries table).
     */
    @Column(name = "num_inscricao")
    private Long numInscricao;

    /**
     * Program code. DDM: AD COD-PROGRAMA A 4 (DE).
     * By value — NOT a FK (Payments never joins to Programs table).
     */
    @NotNull
    @Convert(converter = com.datacorp.app.shared.kernel.CodProgramaConverter.class)
    @Column(name = "cod_programa", nullable = false, length = 4)
    private CodPrograma codPrograma;

    /**
     * Payment competência (AAAAMM). DDM: AE ANO-MES-REF N 6 (DE).
     * Partition key for the {@code pagamento} table (see V4 migration).
     * Unique together with {@link #cpf} per REQ-030.
     */
    @NotNull
    @Convert(converter = com.datacorp.app.shared.kernel.CompetenciaConverter.class)
    @Column(name = "ano_mes_ref", nullable = false)
    private Competencia competencia;

    /** DDM: AF NUM-CICLO N 6. Batch processing cycle number. */
    @Column(name = "num_ciclo")
    private Integer numCiclo;

    // ── Payment type (designed addition — not explicit in DDM) ─────────────

    /**
     * Payment type: N=normal, D=décimo (13th salary), T=terceiro (origin unknown, OQ).
     * Not an explicit DDM field; inferred from calculation context (December = 'D', REQ-022).
     * FIXME: confirm 'T' (TERCEIRO) semantics with stakeholders (no legacy program writes it).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "tipo_pgto", length = 1)
    private TipoPgto tipoPgto;

    public enum TipoPgto { N, D, T }

    // ── Monetary values ────────────────────────────────────────────────────────

    /**
     * Gross benefit value before discounts. DDM: BA VLR-BRUTO N 9.2.
     * All values TRUNCATED to 2 decimal places (REQ-021, never rounded).
     */
    @Column(name = "vlr_bruto", nullable = false, precision = 9, scale = 2)
    private BigDecimal vlrBruto;

    /**
     * Net value (gross − discounts, floored at 0). DDM: BB VLR-LIQUIDO N 9.2.
     * REQ-028: net cannot be negative.
     */
    @Column(name = "vlr_liquido", nullable = false, precision = 9, scale = 2)
    private BigDecimal vlrLiquido;

    /**
     * Sum of all applied discounts. DDM: BC VLR-DESCONTO-TOTAL N 7.2.
     * 30% cap applied to non-judicial discounts (REQ-026).
     */
    @Column(name = "vlr_desconto_total", nullable = false, precision = 9, scale = 2)
    private BigDecimal vlrDescontoTotal;

    /**
     * 13th-salary bonus or Christmas allowance (December only, tipo=D).
     * Designed addition — not an explicit DDM field; computed by CalculoBeneficioService (REQ-022/023).
     */
    @Column(name = "vlr_abono", precision = 9, scale = 2)
    private BigDecimal vlrAbono;

    // ── PE Group GRP-DESCONTO (CA) — @ElementCollection per ADR-003 ──────────

    /**
     * Applied discounts. DDM: CA GRP-DESCONTO PE max 8 occurrences.
     * Stored in child table {@code payments.pagamento_desconto} (ADR-003).
     * Indexed on {@code tipo_desconto} for REQ-025/026/027 queries.
     */
    @ElementCollection(fetch = FetchType.LAZY)
    @CollectionTable(
        name = "pagamento_desconto",
        schema = "payments",
        joinColumns = @JoinColumn(name = "num_pagamento"),
        indexes = {
            @Index(name = "idx_pgto_dsct_tipo", columnList = "tipo_desconto"),
            @Index(name = "idx_pgto_dsct_pagamento", columnList = "num_pagamento")
        }
    )
    @OrderColumn(name = "ocorrencia_idx")
    private List<Desconto> descontos = new ArrayList<>();

    // ── Status and processing ───────────────────────────────────────────────

    /**
     * Payment status. DDM: DA SIT-PAGAMENTO A 1.
     * ADR-002: resolved legacy 'E'/'P'/'C' collision. Transition validated via
     * {@link StatusPagamento#validateTransitionTo(StatusPagamento)}.
     * REQ-029 (initial GERADO), REQ-032 (PAGO/DEVOLVIDO/ERRO).
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "sit_pagamento", nullable = false, length = 12)
    private StatusPagamento status;

    /** DDM: DB DT-GERACAO N 8 (DE, YYYYMMDD → LocalDate). REQ-029. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_geracao")
    private LocalDate dtGeracao;

    /** DDM: DC HR-GERACAO N 6 (HHMMSS → LocalTime). */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalTimeN6Converter.class)
    @Column(name = "hr_geracao")
    private LocalTime hrGeracao;

    /** DDM: DD DT-EMISSAO N 8 (YYYYMMDD → LocalDate). Null until remessa is sent. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_emissao")
    private LocalDate dtEmissao;

    /** DDM: DE DT-CONFIRMACAO N 8. Null until bank confirms. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_confirmacao")
    private LocalDate dtConfirmacao;

    /** DDM: DF DT-CANCELAMENTO N 8. Null unless cancelled. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_cancelamento")
    private LocalDate dtCancelamento;

    /** DDM: DG MOT-CANCELAMENTO A 3. Cancellation reason code (internal table). Nullable. */
    @Column(name = "mot_cancelamento", length = 3)
    private String motCancelamento;

    // ── Monetary correction (designed addition) ──────────────────────────────

    /**
     * Whether IPCA monetary correction has been applied. REQ-034.
     * Designed addition — not an explicit DDM field. Prevents double-correction (idempotency).
     */
    @Column(name = "ind_corrigido", nullable = false)
    private boolean indCorrigido = false;

    /** IPCA correction value applied. Null until correction runs. REQ-034. */
    @Column(name = "vlr_correcao", precision = 9, scale = 2)
    private BigDecimal vlrCorrecao;

    /** Date correction was applied. REQ-034. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_correcao")
    private LocalDate dtCorrecao;

    // ── Bank routing data (embedded, GRP EA..EE) ─────────────────────────────

    /** DDM fields EA-EE: bank routing data per payment. MYS-010 resolved. */
    @Embedded
    private DadosBancarios dadosBancarios;

    // ── SIAFI integration (embedded, GRP FA..FE) ─────────────────────────────

    /** DDM fields FA-FE: SIAFI government finance system integration (added 2002). */
    @Embedded
    private IntegracaoSiafi integracaoSiafi;

    // ── CNAB reconciliation (embedded, GRP GA..GE) ───────────────────────────

    /** DDM fields GA-GE: bank return / reconciliation data. REQ-032/033. */
    @Embedded
    private ConciliacaoBancaria conciliacaoBancaria;

    // ── File hashes (added 2015) ──────────────────────────────────────────────

    /**
     * SHA-256 of the remessa file that included this payment.
     * DDM: HA HASH-ARQ-REMESSA A 64.
     */
    @Column(name = "hash_arq_remessa", length = 64)
    private String hashArqRemessa;

    /**
     * SHA-256 of the retorno file from the bank.
     * DDM: HB HASH-ARQ-RETORNO A 64.
     */
    @Column(name = "hash_arq_retorno", length = 64)
    private String hashArqRetorno;

    // ── Audit control (GRP IA..IF) ─────────────────────────────────────────

    /** DDM: IA DT-INCLUSAO N 8 (YYYYMMDD). Set on creation; never updated. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_inclusao", updatable = false)
    private LocalDate dtInclusao;

    /** DDM: IB HR-INCLUSAO N 6 (HHMMSS). Set on creation; never updated. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalTimeN6Converter.class)
    @Column(name = "hr_inclusao", updatable = false)
    private LocalTime hrInclusao;

    /** DDM: IC USR-INCLUSAO A 8. User/batch that created the record ('BATCH' for folha). */
    @Column(name = "usr_inclusao", length = 8, updatable = false)
    private String usrInclusao;

    /** DDM: ID DT-ULT-ALTERACAO N 8 (YYYYMMDD). Updated on every mutation. */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalDateN8Converter.class)
    @Column(name = "dt_ult_alteracao")
    private LocalDate dtUltAlteracao;

    /** DDM: IE HR-ULT-ALTERACAO N 6 (HHMMSS). */
    @Convert(converter = com.datacorp.app.shared.kernel.LocalTimeN6Converter.class)
    @Column(name = "hr_ult_alteracao")
    private LocalTime hrUltAlteracao;

    /** DDM: IF USR-ULT-ALTERACAO A 8. */
    @Column(name = "usr_ult_alteracao", length = 8)
    private String usrUltAlteracao;

    // ── Constructors ──────────────────────────────────────────────────────────

    protected Pagamento() {}

    /**
     * Factory for FolhaService — creates a new GERADO payment.
     * REQ-029: initial status = GERADO. REQ-030: unique (cpf, competencia).
     */
    public static Pagamento criar(Cpf cpf, Long numInscricao, CodPrograma codPrograma,
                                   Competencia competencia, BigDecimal vlrBruto,
                                   BigDecimal vlrDescontoTotal, BigDecimal vlrLiquido,
                                   TipoPgto tipoPgto) {
        Pagamento p = new Pagamento();
        p.cpf = cpf;
        p.numInscricao = numInscricao;
        p.codPrograma = codPrograma;
        p.competencia = competencia;
        p.vlrBruto = vlrBruto;
        p.vlrDescontoTotal = vlrDescontoTotal;
        p.vlrLiquido = vlrLiquido;
        p.tipoPgto = tipoPgto != null ? tipoPgto : TipoPgto.N;
        p.status = StatusPagamento.GERADO;
        p.dtGeracao = LocalDate.now();
        p.dtInclusao = LocalDate.now();
        p.hrInclusao = LocalTime.now();
        p.usrInclusao = "BATCH";
        return p;
    }

    /** Adds a discount to this payment. */
    public void addDesconto(Desconto desconto) {
        this.descontos.add(desconto);
        this.vlrDescontoTotal = descontos.stream()
                .map(Desconto::getVlrDesconto)
                .reduce(java.math.BigDecimal.ZERO, java.math.BigDecimal::add);
    }

    /** Updates reconciliation data. */
    public void reconciliar(ConciliacaoBancaria conciliacao) {
        this.conciliacaoBancaria = conciliacao;
        this.dtUltAlteracao = LocalDate.now();
    }

    // ── Domain behaviour ──────────────────────────────────────────────────────

    /**
     * Transitions the payment to a new status, enforcing the canonical state machine.
     * ADR-002. REQ-032.
     */
    public void transitionTo(StatusPagamento newStatus) {
        this.status.validateTransitionTo(newStatus);
        this.status = newStatus;
    }

    /** Applies IPCA correction if not already corrected (idempotency, REQ-034). */
    public void applyCorrecao(BigDecimal valorCorrecao, LocalDate dataCorrecao) {
        if (this.indCorrigido) {
            return; // idempotent — silent no-op
        }
        this.vlrCorrecao = valorCorrecao;
        this.dtCorrecao = dataCorrecao;
        this.indCorrigido = true;
    }

    /** Read-only view of the discounts collection. */
    public List<Desconto> getDescontos() {
        return Collections.unmodifiableList(descontos);
    }

    // ── Getters (no public setters — mutation through domain methods) ─────────

    public Long getNumPagamento()                   { return numPagamento; }
    public Cpf getCpf()                             { return cpf; }
    public CodPrograma getCodPrograma()             { return codPrograma; }
    public Competencia getCompetencia()             { return competencia; }
    public StatusPagamento getStatus()              { return status; }
    public BigDecimal getVlrBruto()                 { return vlrBruto; }
    public BigDecimal getVlrLiquido()               { return vlrLiquido; }
    public BigDecimal getVlrDescontoTotal()         { return vlrDescontoTotal; }
    public BigDecimal getVlrAbono()                 { return vlrAbono; }
    public TipoPgto getTipoPgto()                   { return tipoPgto; }
    public boolean isIndCorrigido()                 { return indCorrigido; }
    public BigDecimal getVlrCorrecao()              { return vlrCorrecao; }
    public LocalDate getDtCorrecao()                { return dtCorrecao; }
    public LocalDate getDtGeracao()                 { return dtGeracao; }
    public DadosBancarios getDadosBancarios()       { return dadosBancarios; }
    public ConciliacaoBancaria getConciliacaoBancaria() { return conciliacaoBancaria; }
}
