-- ============================================================================
-- V4__create_payments_schema.sql
-- Flyway migration for the Payments bounded context (PAGAMENTO FNR 152).
-- Generated from PAGAMENTO.ddm (01-arqueologia/legado-sifap/adabas-ddms/).
--
-- ADR-002: StatusPagamento canonical enum (resolves SIT-PAGAMENTO collision)
-- ADR-003: GRP-DESCONTO as pagamento_desconto child table with partition index
--
-- ⚠️  BEFORE RUNNING:
--   1. Resolve OQ-01 (status de-para) with SENARC/CGPB — the
--      pagamento_status_depara note file must be signed off before any
--      data migration loads rows from the legacy PAGAMENTO file.
--   2. Validate partition range covers the full legacy data span (1998–present).
--   3. Test rollback section in a staging environment first.
--
-- Rollback: see the DROP section at the bottom.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Schema
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS payments;

-- ----------------------------------------------------------------------------
-- Domain type: status enum (ADR-002)
-- Canonical set — NOTE: 'G','P','E','C','D','X','R' (legacy chars) are NOT
-- stored here. The ConciliacaoService and FolhaService write the enum name.
-- De-para table for legacy migration: db/migration/notes/status-depara.md
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_pagamento'
                   AND typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'payments')) THEN
        CREATE TYPE payments.status_pagamento AS ENUM (
            'GERADO',    -- folha generated by FolhaService (legacy 'G')
            'EMITIDO',   -- remessa sent to bank (legacy DDM 'E')
            'PAGO',      -- bank confirmed credit, ret '00' (legacy 'P' in BATCHCON)
            'DEVOLVIDO', -- bank returned, ret '01'         (legacy 'D')
            'ERRO',      -- bank error, ret '02'            (legacy 'E' in BATCHCON)
            'CANCELADO', -- cancelled (legacy 'C' — orphan, source TBD per OQ-01)
            'ESTORNADO'  -- reversed after payment          (legacy 'E' in BATCHREL)
        );
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- Sequence for NUM-PAGAMENTO (replaces Adabas auto-increment mechanism)
-- Allocation size 50 matches @SequenceGenerator allocationSize in entity.
-- ----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS payments.pagamento_num_seq
    START WITH 1
    INCREMENT BY 50
    NO MAXVALUE
    CACHE 50;

-- ----------------------------------------------------------------------------
-- Main table: pagamento
-- Range-partitioned by ano_mes_ref (NUMERIC(6) = AAAAMM).
-- ADR-003: partition enables efficient archival of historic months (~180M rows).
-- ============================================================================
-- NOTE: PostgreSQL range partitioning requires creating child partitions
-- separately (see partition management section below).
-- ----------------------------------------------------------------------------
CREATE TABLE payments.pagamento (
    -- ── Identity (DDM: AA-AF) ──────────────────────────────────────────────
    num_pagamento       BIGINT          NOT NULL DEFAULT nextval('payments.pagamento_num_seq'),
    num_cpf             CHAR(11)        NOT NULL,   -- DDM: AB (DE)
    num_inscricao       BIGINT,                     -- DDM: AC cross-ref to BENEFICIARIO
    cod_programa        CHAR(4)         NOT NULL,   -- DDM: AD (DE)
    ano_mes_ref         NUMERIC(6)      NOT NULL,   -- DDM: AE (DE) partition key (AAAAMM)
    num_ciclo           INTEGER,                    -- DDM: AF

    -- ── Tipo pagamento (designed addition, not in DDM) ────────────────────
    -- FIXME: confirm 'T' (TERCEIRO) semantics — no legacy program writes it
    tipo_pgto           CHAR(1) CHECK (tipo_pgto IN ('N','D','T')),

    -- ── Monetary values (DDM: BA-BC) ──────────────────────────────────────
    -- All NUMERIC(9,2) per DDM. Truncated, never rounded (REQ-021).
    vlr_bruto           NUMERIC(9,2)    NOT NULL,
    vlr_liquido         NUMERIC(9,2)    NOT NULL CHECK (vlr_liquido >= 0),  -- REQ-028
    vlr_desconto_total  NUMERIC(9,2)    NOT NULL DEFAULT 0,

    -- Abono natalino (designed addition — 13th salary bonus, REQ-022/023)
    vlr_abono           NUMERIC(9,2),

    -- ── Status (DDM: DA) ──────────────────────────────────────────────────
    sit_pagamento       payments.status_pagamento NOT NULL,  -- ADR-002

    -- ── Status timestamps (DDM: DB-DG) ────────────────────────────────────
    dt_geracao          DATE,           -- DDM: DB (DE, YYYYMMDD)
    hr_geracao          TIME,           -- DDM: DC
    dt_emissao          DATE,           -- DDM: DD
    dt_confirmacao      DATE,           -- DDM: DE
    dt_cancelamento     DATE,           -- DDM: DF
    mot_cancelamento    CHAR(3),        -- DDM: DG

    -- ── Monetary correction (designed addition) ───────────────────────────
    ind_corrigido       BOOLEAN         NOT NULL DEFAULT FALSE,  -- REQ-034
    vlr_correcao        NUMERIC(9,2),
    dt_correcao         DATE,

    -- ── Bank routing (DDM: EA-EE, MYS-010 resolved) ───────────────────────
    cod_banco           CHAR(3),        -- DDM: EA (FEBRABAN)
    cod_agencia         VARCHAR(6),     -- DDM: EB
    num_conta           VARCHAR(13),    -- DDM: EC
    tipo_conta          CHAR(1)  CHECK (tipo_conta IN ('C','P')),  -- DDM: ED
    cod_operacao        CHAR(3),        -- DDM: EE (Caixa Econômica, nullable)

    -- ── SIAFI integration (DDM: FA-FE, added 2002) ────────────────────────
    num_ob_siafi        VARCHAR(12),    -- DDM: FA (Ordem Bancária SIAFI)
    num_ne_siafi        VARCHAR(12),    -- DDM: FB (Nota de Empenho SIAFI)
    cod_ug_emitente     VARCHAR(6),     -- DDM: FC
    cod_gestao          VARCHAR(5),     -- DDM: FD
    sit_integ_siafi     CHAR(1) CHECK (sit_integ_siafi IN ('I','P','E')),  -- DDM: FE

    -- ── CNAB reconciliation (DDM: GA-GE) ──────────────────────────────────
    dt_conciliacao      DATE,           -- DDM: GA
    sit_conciliacao     CHAR(1) CHECK (sit_conciliacao IN ('C','D','P','N')),  -- DDM: GB
    vlr_conciliado      NUMERIC(9,2),   -- DDM: GC
    cod_retorno_banco   CHAR(2),        -- DDM: GD
    des_retorno_banco   VARCHAR(40),    -- DDM: GE

    -- ── File hashes (DDM: HA-HB, added 2015) ──────────────────────────────
    hash_arq_remessa    CHAR(64),       -- DDM: HA SHA-256
    hash_arq_retorno    CHAR(64),       -- DDM: HB SHA-256

    -- ── Audit control (DDM: IA-IF) ────────────────────────────────────────
    dt_inclusao         DATE            NOT NULL DEFAULT CURRENT_DATE,  -- DDM: IA
    hr_inclusao         TIME            NOT NULL DEFAULT CURRENT_TIME,  -- DDM: IB
    usr_inclusao        VARCHAR(8)      NOT NULL DEFAULT 'SYSTEM',      -- DDM: IC
    dt_ult_alteracao    DATE,           -- DDM: ID
    hr_ult_alteracao    TIME,           -- DDM: IE
    usr_ult_alteracao   VARCHAR(8),     -- DDM: IF

    PRIMARY KEY (num_pagamento, ano_mes_ref)  -- compound PK required for range partition
) PARTITION BY RANGE (ano_mes_ref);

-- Unique constraint enforcing REQ-030 (one payment per beneficiary per month)
CREATE UNIQUE INDEX uq_pagamento_cpf_competencia
    ON payments.pagamento (num_cpf, ano_mes_ref);

-- Super-descriptor S1: AB + AE — CPF + COMPETENCIA
CREATE INDEX idx_pagamento_s1_cpf_competencia
    ON payments.pagamento (num_cpf, ano_mes_ref);

-- Super-descriptor S2: AD + AE + DA — PROGRAMA + COMPET + SITUACAO
CREATE INDEX idx_pagamento_s2_prog_comp_status
    ON payments.pagamento (cod_programa, ano_mes_ref, sit_pagamento);

-- Super-descriptor S3: AF + DA — CICLO + SITUACAO
CREATE INDEX idx_pagamento_s3_ciclo_status
    ON payments.pagamento (num_ciclo, sit_pagamento);

-- DE field: DT-GERACAO
CREATE INDEX idx_pagamento_dt_geracao ON payments.pagamento (dt_geracao);

-- ----------------------------------------------------------------------------
-- Partition management
-- Covers 1998–current + a 2-year rolling window.
-- NOTE: Add new partitions yearly via a scheduled job or separate migration.
-- ----------------------------------------------------------------------------
CREATE TABLE payments.pagamento_1998 PARTITION OF payments.pagamento
    FOR VALUES FROM (199801) TO (199901);
CREATE TABLE payments.pagamento_1999 PARTITION OF payments.pagamento
    FOR VALUES FROM (199901) TO (200001);
CREATE TABLE payments.pagamento_2000 PARTITION OF payments.pagamento
    FOR VALUES FROM (200001) TO (200101);
CREATE TABLE payments.pagamento_2001 PARTITION OF payments.pagamento
    FOR VALUES FROM (200101) TO (200201);
CREATE TABLE payments.pagamento_2002 PARTITION OF payments.pagamento
    FOR VALUES FROM (200201) TO (200301);
CREATE TABLE payments.pagamento_2003 PARTITION OF payments.pagamento
    FOR VALUES FROM (200301) TO (200401);
CREATE TABLE payments.pagamento_2004 PARTITION OF payments.pagamento
    FOR VALUES FROM (200401) TO (200501);
CREATE TABLE payments.pagamento_2005 PARTITION OF payments.pagamento
    FOR VALUES FROM (200501) TO (200601);
CREATE TABLE payments.pagamento_2006 PARTITION OF payments.pagamento
    FOR VALUES FROM (200601) TO (200701);
CREATE TABLE payments.pagamento_2007 PARTITION OF payments.pagamento
    FOR VALUES FROM (200701) TO (200801);
CREATE TABLE payments.pagamento_2008 PARTITION OF payments.pagamento
    FOR VALUES FROM (200801) TO (200901);
CREATE TABLE payments.pagamento_2009 PARTITION OF payments.pagamento
    FOR VALUES FROM (200901) TO (201001);
CREATE TABLE payments.pagamento_2010 PARTITION OF payments.pagamento
    FOR VALUES FROM (201001) TO (201101);
CREATE TABLE payments.pagamento_2011 PARTITION OF payments.pagamento
    FOR VALUES FROM (201101) TO (201201);
CREATE TABLE payments.pagamento_2012 PARTITION OF payments.pagamento
    FOR VALUES FROM (201201) TO (201301);
CREATE TABLE payments.pagamento_2013 PARTITION OF payments.pagamento
    FOR VALUES FROM (201301) TO (201401);
CREATE TABLE payments.pagamento_2014 PARTITION OF payments.pagamento
    FOR VALUES FROM (201401) TO (201501);
CREATE TABLE payments.pagamento_2015 PARTITION OF payments.pagamento
    FOR VALUES FROM (201501) TO (201601);
CREATE TABLE payments.pagamento_2016 PARTITION OF payments.pagamento
    FOR VALUES FROM (201601) TO (201701);
CREATE TABLE payments.pagamento_2017 PARTITION OF payments.pagamento
    FOR VALUES FROM (201701) TO (201801);
CREATE TABLE payments.pagamento_2018 PARTITION OF payments.pagamento
    FOR VALUES FROM (201801) TO (201901);
CREATE TABLE payments.pagamento_2019 PARTITION OF payments.pagamento
    FOR VALUES FROM (201901) TO (202001);
CREATE TABLE payments.pagamento_2020 PARTITION OF payments.pagamento
    FOR VALUES FROM (202001) TO (202101);
CREATE TABLE payments.pagamento_2021 PARTITION OF payments.pagamento
    FOR VALUES FROM (202101) TO (202201);
CREATE TABLE payments.pagamento_2022 PARTITION OF payments.pagamento
    FOR VALUES FROM (202201) TO (202301);
CREATE TABLE payments.pagamento_2023 PARTITION OF payments.pagamento
    FOR VALUES FROM (202301) TO (202401);
CREATE TABLE payments.pagamento_2024 PARTITION OF payments.pagamento
    FOR VALUES FROM (202401) TO (202501);
CREATE TABLE payments.pagamento_2025 PARTITION OF payments.pagamento
    FOR VALUES FROM (202501) TO (202601);
CREATE TABLE payments.pagamento_2026 PARTITION OF payments.pagamento
    FOR VALUES FROM (202601) TO (202701);
CREATE TABLE payments.pagamento_2027 PARTITION OF payments.pagamento
    FOR VALUES FROM (202701) TO (202801);
-- DEFAULT partition catches anything outside the declared ranges (safety net)
CREATE TABLE payments.pagamento_default PARTITION OF payments.pagamento DEFAULT;

-- ----------------------------------------------------------------------------
-- Child table: pagamento_desconto
-- GRP-DESCONTO (CA, PE, max 8) — ADR-003: @ElementCollection per Desconto.
-- Inherits partition key from parent via num_pagamento + ano_mes_ref (included
-- in order to co-locate desconto rows with their parent partition).
-- ----------------------------------------------------------------------------
CREATE TABLE payments.pagamento_desconto (
    num_pagamento   BIGINT          NOT NULL,
    ano_mes_ref     NUMERIC(6)      NOT NULL,   -- for partition co-location
    ocorrencia_idx  SMALLINT        NOT NULL,   -- PE occurrence order (0-based)

    -- DDM: CB TIPO-DESCONTO A 3 — REQ-025/026/027
    tipo_desconto   VARCHAR(3)      NOT NULL,

    -- DDM: CC VLR-DESCONTO N 7.2
    vlr_desconto    NUMERIC(9,2)    NOT NULL,

    -- DDM: CD PCT-DESCONTO N 3.2
    pct_desconto    NUMERIC(5,2),

    -- DDM: CE NUM-PROCESSO A 20 (required when tipo_desconto = 'JD', REQ-027)
    num_processo    VARCHAR(20),

    -- DDM: CF DT-INICIO-DSCT N 8 (YYYYMMDD → DATE)
    dt_inicio_dsct  DATE,

    -- DDM: CG DT-FIM-DSCT N 8 (YYYYMMDD → DATE; NULL = indefinido)
    dt_fim_dsct     DATE,

    PRIMARY KEY (num_pagamento, ano_mes_ref, ocorrencia_idx),

    FOREIGN KEY (num_pagamento, ano_mes_ref)
        REFERENCES payments.pagamento (num_pagamento, ano_mes_ref)
        ON DELETE CASCADE
);

-- Index required by REQ-025/026/027 (sum/filter by discount type)
CREATE INDEX idx_pgto_dsct_tipo       ON payments.pagamento_desconto (tipo_desconto);
CREATE INDEX idx_pgto_dsct_pagamento  ON payments.pagamento_desconto (num_pagamento, ano_mes_ref);

-- Check: judicial discount must have a process number (REQ-027)
ALTER TABLE payments.pagamento_desconto
    ADD CONSTRAINT chk_judicial_numprocesso
    CHECK (tipo_desconto <> 'JD' OR num_processo IS NOT NULL);

-- Comments for DBA reference
COMMENT ON TABLE payments.pagamento IS
    'Payment records from SIFAP PAGAMENTO FNR 152. ~180M rows (1998–present), '
    'partitioned by ano_mes_ref. Status machine: ADR-002. Discounts: ADR-003.';
COMMENT ON TABLE payments.pagamento_desconto IS
    'Applied discounts per payment. Adabas GRP-DESCONTO PE (max 8). ADR-003.';
COMMENT ON COLUMN payments.pagamento.sit_pagamento IS
    'ADR-002 canonical status. De-para from legacy 1-char codes in '
    'db/migration/notes/status-depara.md (requires SENARC/CGPB sign-off, OQ-01).';

-- ============================================================================
-- Rollback
-- To undo this migration (in reverse order):
--
-- DROP TABLE IF EXISTS payments.pagamento_desconto;
-- DROP TABLE IF EXISTS payments.pagamento CASCADE;
-- DROP SEQUENCE IF EXISTS payments.pagamento_num_seq;
-- DROP TYPE IF EXISTS payments.status_pagamento;
-- DROP SCHEMA IF EXISTS payments CASCADE;  -- only if schema was created here
-- ============================================================================
